name:         place-cursor-at
synopsis:     A utility for X11 that moves the mouse cursor using the keyboard
version:      1.0.0
license:      GPL-3
license-file: LICENSE
author:       Viacheslav Lotsmanov
copyright:    Copyright © 2017–2021 Viacheslav Lotsmanov
maintainer:   Viacheslav Lotsmanov <lotsmanov89@gmail.com>
category:     Utility, GUI, Desktop, Desktop Environment, X11
github:       unclechu/place-cursor-at

extra-source-files: README.md

tested-with: GHC ==8.10.4 || ==8.8.4 || ==8.6.4

dependencies:
  - base >= 4.12 && < 5
  - base-unicode-symbols ^>= 0.2
  - X11 >= 1.9 && < 2

ghc-options:
  - -threaded

extra-libraries:
  - Xinerama

executables:
  place-cursor-at:
    source-dirs: src
    main:        place-cursor-at.hs
