# also tested with lts-14.27 (ghc 8.6.5)
resolver: lts-16.6 # ghc 8.8.3

system-ghc: false
packages: [.]

nix:
  packages:
    - xorg.libX11
    - xorg.libXrandr
    - xorg.libXScrnSaver
    - xorg.libXext
    - xorg.libXinerama
