# Also tested with lts-13.19 (ghc 8.6.4).
#
# Test older one using Nix:
#   nix-shell \
#     --argstr nixpkgs-release 19.03 \
#     --arg buildExecutable false \
#     --arg withStack true \
#     --arg withStackNixDependencies true \
#     --run '[[ $(ghc --numeric-version) == 8.6.4 ]] && \
#       stack build --system-ghc --no-nix --resolver=lts-13.19 && \
#       stack exec --system-ghc --no-nix --resolver=lts-13.19 \
#       place-cursor-at'
#
# Test current one using Nix:
#   nix-shell \
#     --arg buildExecutable false \
#     --arg withStack true \
#     --run 'stack build --system-ghc && \
#       stack exec --system-ghc -- place-cursor-at'
#
resolver: lts-20.23 # ghc 9.2.7

system-ghc: false
packages: [.]

nix:
  packages:
    - xorg.libX11
    - xorg.libXrandr
    - xorg.libXScrnSaver
    - xorg.libXext
    - xorg.libXinerama
